FROM apache/airflow:2.10.4

# Copia o airflow.cfg local para dentro do contêiner
COPY airflow.cfg /opt/airflow/airflow.cfg

# (Opcional) Se quiser setar alguma variável de ambiente para apontar pro arquivo:
ENV AIRFLOW_CONFIG=/opt/airflow/airflow.cfg

# Se tiver mais arquivos de configuração, bibliotecas extras, etc., copie aqui
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
